name: Python Package Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: flappy-bird

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          set -e
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

      - name: Verify environment
        run: |
          source venv/bin/activate
          python -m pip list

      - name: Create tarball
        run: |
          tar --exclude-vcs --exclude='./venv' -czvf ${PROJECT_NAME}.tar.gz .
          ls -la ${PROJECT_NAME}.tar.gz

      - name: Upload Release Assets to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: ${PROJECT_NAME}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
