name: Python Package Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: flappy-bird

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; else echo "No requirements.txt found"; fi
          deactivate  # Đảm bảo venv hoàn tất trước khi tiếp tục

      - name: Verify environment
        run: |
          source venv/bin/activate
          python -m pip list
          deactivate

      - name: Prepare release directory
        run: |
          mkdir -p /tmp/release
          cp -r . /tmp/release/  # Sao chép toàn bộ thư mục gốc (bao gồm venv)
          sync  # Đợi tất cả hoạt động ghi file hoàn tất
          sleep 2  # Thêm thời gian chờ để đảm bảo ổn định
          cd /tmp/release
          ls -la  # Kiểm tra nội dung trước khi nén

      - name: Create tarball
        run: |
          cd /tmp/release
          tar --exclude='./.git' -czvf ${PROJECT_NAME}.tar.gz .
          ls -la  # Kiểm tra xem file tar.gz đã được tạo chưa

      - name: Upload Release Assets to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: release-files
          path: /tmp/release/${PROJECT_NAME}.tar.gz

      - name: Upload Release Assets to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/release/${PROJECT_NAME}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
