name: Python Package Release

on:
  push:
    tags:
      - 'v*'  # Kích hoạt workflow khi có tag bắt đầu bằng "v"

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    env:
      PROJECT_NAME: flappy-bird  # Tạo biến tên dự án

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Lấy mã nguồn từ GitHub

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Chọn phiên bản Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv  # Tạo môi trường ảo
          source venv/bin/activate  # Kích hoạt môi trường ảo
          pip install -r requirements.txt  # Cài đặt thư viện

      - name: Verify environment
        run: |
          source venv/bin/activate
          python -m pip list  # Liệt kê các package đã cài đặt

      - name: Build the package
        run: |
          source venv/bin/activate  # Đảm bảo môi trường ảo đã được kích hoạt
          mkdir -p /tmp  # Create a temporary directory
          mkdir -p /tmp/release
          cp -r * /tmp/release  # Copy all files to the temporary directory
          cd /tmp/release
          ls -la # Kiểm tra file trước khi nén
          tar -czvf ${PROJECT_NAME}.tar.gz .
          ls -la # Kiểm tra lại xem file tar.gz có được tạo không
 # Dùng biến tên dự án để tạo tên file release

      - name: Upload Release Assets to GitHub
        uses: softprops/action-gh-release@v1  # Upload các file release lên GitHub
        with:
          files: |
            /tmp/release/${PROJECT_NAME}.tar.gz  # Upload bản release với tên dựa trên biến
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub tự động tạo token khi sử dụng GitHub Actions
