name: Python Package Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: flappy-bird

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; else echo "No requirements.txt found"; fi

      - name: Verify environment
        run: |
          source venv/bin/activate
          python -m pip list

      - name: Prepare release directory
        run: |
          mkdir -p /tmp
          mkdir -p /tmp/release
          rsync -av --exclude='tmp/release' ./ /tmp/release/
          sync
          sleep 2
          cd /tmp/release
          ls -la

      - name: Create tarball
        run: |
          cd /tmp/release
          tar --exclude='./.git' -czvf ${PROJECT_NAME}.tar.gz .
          ls -la

      - name: Upload Release Assets to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/release/${PROJECT_NAME}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
